### ISSUE TITLE
Error `this._credential.getCredential is not a function`

### ISSUE THREAD

**Issue by Neumann-Nils** [aliyun/darabonba-openapi#156]
When updating to the newest version of `@alicloud/openapi-client` to `0.4.10`, we receive the following error when trying to run `createClientCertificateWithCsrWithOptions`:

```
this._credential.getCredential is not a function
```

Looking into the changes, this error is caused by the changes introduced in https://github.com/aliyun/darabonba-openapi/pull/149. We have debugged the problem and in our case, the `this._credential` only has our credential configuration but indeed no `getCredential` function.

Can you advise us how to fix this issue?

**Comment by JacksonTian** [comment]
Please update the indirect module @alicloud/credentials package to latest version.

**Comment by Neumann-Nils** [comment]
@JacksonTian That seems to fix it, thanks :)
